import Head from "next/head";

//components
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import About from "../components/About";
import Gallary from "../components/Gallary";

//images
import Header_img from "../public/header.jpg";
import Jelly from "../public/jelly.jpg";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
        items={[
          { name: "Home", href: "#" },
          { name: "About Nature", href: "#about" },
          { name: "Gallary", href: "#gallary" },
          { name: "Contact Us", href: "#contact" },
        ]}
        title="Nature"
      />
      <Header img={Header_img} />
      <About img={Jelly} />
      <Gallary />
    </div>
  );
}
